import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { ReactElement } from "react";
import AppLayout from "@/layout/appLayout";
import HomeCarousel from "@/domains/home/homeCarosel";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Techpack test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeCarousel />
    </>
  );
}

Home.getLayout = (page: ReactElement) => <AppLayout>{page}</AppLayout>;
